string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)"
  KMC_THIN_FILM_VERSION_MATCH ${KMC_THIN_FILM_VERSION_STRING})

set(KMC_THIN_FILM_MAJOR_VERSION ${CMAKE_MATCH_1})
set(KMC_THIN_FILM_MINOR_VERSION ${CMAKE_MATCH_2})
set(KMC_THIN_FILM_SUB_VERSION ${CMAKE_MATCH_3})
